### ISSUE TITLE
Rever wiped out the changelog?

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-incubator/ensureconda#5]
cc @scopatz

**Comment by scopatz** [comment]
Is there more context here?  What commands were run?

**Comment by mariusvniekerk** [comment]
Just regular `rever {version}` statements. It looks like it has never
actually made a changelog.  So the changelog just step just seems to have
deleted the news files

**Comment by scopatz** [comment]
Was `rever setup` ever run?
